services:
  postgres:
    image: postgres
    container_name: test-postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: open-library
      POSTGRES_USER: postgres
    ports:
      - "5431:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
      - ./sql:/docker-entrypoint-initdb.d
      
  api:
    build: ./api 
    container_name: test-api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/open-library
    depends_on:
      - postgres
    volumes:
      - ./dumps:/app/dumps

volumes:
  postgres-data: